URL_SERVICE = "https://bf450c78-8456-4fe2-bdd9-cc3bfc783eae.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
MAIN_KITS_PATH = "/api/v1/kits/"
